server:
  port: 8101
spring:
  application:
    name: bookservice
eureka:
  client:
    # 跟上面一样，需要指向Eureka服务端地址，这样才能进行注册
    service-url:
      defaultZone: http://localhost:8801/eureka, http://localhost:8802/eureka
